name: 4n6
favicon: null
layout_spectrum: 0.9327032626606524
typography_spectrum: 0.4831391363404691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25345478393137455
  lightness: 0.8091406128369272
  saturation: 0.6440997940953821
  rhythmicContrast: 0.14268405153416097
purpose: []
