typography_spectrum: 0.26253
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3f270f'
    - '#8c8d53'
    - '#5c623e'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8293
analytics:
  google: null
  facebook: null
  twitter: null
name: 4n6
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: forensicDesign
description: the confluence of design and technology
purpose: []
