typography_spectrum: 0.031393730314448476
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.1830081723164767
  lightness: 0.5859941034577787
  saturation: 0.3288151703309268
  rhythmicContrast: 0.6351828470360488
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7277875323779881
analytics:
  google: null
  facebook: null
  twitter: null
name: 4n6
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: banners
    id: f2150840-4bdd-4c3e-8358-179a5f6bc6fd
    type: content
  - name: video
    id: 144a53ef-cd8b-47b8-bae2-65782b203e91
    type: content
  - name: photography
    id: 5cf5bc22-1774-4e81-9228-50471ba5c639
    type: content
  - name: banner test
    url: 'http://4n6.net/banners/html5/ampm/strawberry/'
    type: external
favicon: null
title: forensicDesign
description: the confluence of art and technology
purpose: []
