typography_spectrum: 0.6280065786559135
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.1830081723164767
  lightness: 0.5859941034577787
  saturation: 0.3288151703309268
  rhythmicContrast: 0.6351828470360488
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5949894024524838
analytics:
  google: null
  facebook: null
  twitter: null
name: 4n6
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: banners
    id: f2150840-4bdd-4c3e-8358-179a5f6bc6fd
    type: content
  - name: video
    id: 144a53ef-cd8b-47b8-bae2-65782b203e91
    type: content
  - name: photography
    id: 5cf5bc22-1774-4e81-9228-50471ba5c639
    type: content
  - name: Graphic FX
    id: b27fbf65-4fbf-47a3-8bfd-ec3b7721f761
    type: content
favicon: null
title: forensicDesign
description: the confluence of art and technology
purpose: []
